gen3_cart_imped_controller:
  type: ee_cart_imped_control/EECartImpedControlPlugin
  root_name: base_link 
  tip_name: end_effector_link 
  default_stiffness: 200
  default_rotational_stiffness: 100
  cartesian_dampening: [1,1,1]
  euler_angle_dampening: [1,1,1]
