gen3_cart_imped_controller:
  gen3_cart_imped_action_node:
    root_name: base_link
    constraints:
      goal:
        time: 0.0
        position:
          x: 0.01
          y: 0.01
          z: 0.01
        orientation:
          x: 0.02
          y: 0.02
          z: 0.02
          w: 0.02
        effort: 0.002
      trajectory:
        effort: -1.0
