gen3_cart_imped_controller:
  gen3_cart_imped_action_node:
    root_name: base_link
    constraints:
      goal:
        time: 0.0
        position:
          x: 0.2
          y: 0.2
          z: 0.2
        orientation:
          x: 0.2
          y: 0.2
          z: 0.2
          w: 0.2
        effort: 0.002
      trajectory:
        effort: -1.0
